name: librebook
description: An ebook downloader.
version: 0.1.0-alpha

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0

  # architecture
  get: ^4.2.5
  get_storage: ^2.0.3

  # database
  sembast: ^3.1.0+2

  # api
  http: ^0.13.3
  html: ^0.15.0

  # misc
  shimmer: ^2.0.0
  cached_network_image: ^3.1.0
  async: ^2.6.1
  lazy_load_refresh_indicator: ^2.0.0
  mime: ^1.0.0
  package_info: ^2.0.2
  md2_tab_indicator:
    git:
      url: git://github.com/westdabestdb/md2_tab_indicator.git
      ref: master
  material_floating_search_bar: ^0.3.4

  # download
  dio: ">=4.0.0 <6.0.0"
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+1
  open_file: ^3.2.1

  # localization
  flutter_localizations:
    sdk: flutter
  global_configuration: ^2.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  assets:
    - lang/
    - assets/icon/
  uses-material-design: true
