name: librebook
description: An ebook downloader.
version: 0.0.1-alpha

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0

  # architecture
  get:
  get_storage:

  # database
  sembast:

  # api
  http:
  html:

  # misc
  shimmer:
  cached_network_image:
  async:
  enhanced_future_builder:
  lazy_load_refresh_indicator:
  flutter_statusbarcolor:
  md2_tab_indicator:
  mime:
  package_info: ^0.4.0+16

  # download
  dio:
  path_provider:
  ext_storage: ^1.0.3
  permission_handler: ^5.0.1+1
  open_file: ^3.0.3

  # localization
  flutter_localizations:
    sdk: flutter
  global_configuration: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  assets:
    - lang/
    - assets/icon/
  uses-material-design: true
