name: librebook
description: An ebook downloader.
version: 0.0.1-alpha

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # architecture
  stacked:
  stacked_services:
  
  # hooks
  flutter_hooks:
  stacked_hooks:
  
  # route
  auto_route:
  
  # injection
  get_it:
  injectable:
  
  # api
  http:
  html:

  #misc
  shimmer:
  cached_network_image:
  async:
  enhanced_future_builder:

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # generator
  build_runner:
  auto_route_generator:
  injectable_generator:

flutter:
  uses-material-design: true
