name: librebook
description: An ebook downloader.
version: 0.0.1-alpha

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0

  # architecture
  get:

  # database
  sembast:

  # api
  http:
  html:

  # misc
  shimmer:
  cached_network_image:
  async:
  enhanced_future_builder:
  lazy_load_refresh_indicator:
  flutter_statusbarcolor:
  outline_material_icons:
  md2_tab_indicator:
  mime:

  #download
  dio:
  path_provider:
  downloads_path_provider_28:
  permission_handler: ^5.0.1+1
  open_file:

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  assets:
    - assets/icon/
  uses-material-design: true
